### PR TITLE
Add function stubs

### PR DESCRIPTION
**Pull request by m-cat**
~~Integration tests should be in a separate `tests` directory to ensure that everything was exported properly.~~

Add function stubs

### CODE REVIEW

**Comment by kwypchlo** [comment]
actually it's pretty common to keep the test files next to the source files, why would we want to move them out?

**Comment by m-cat** [comment]
@kwypchlo I'm used to unit tests being in the same directory and integration tests being in a different directory. Otherwise, having integration tests in the same directory makes it easy to use something that wasn't actually exported. Maybe it's not common practice in JS though

**Comment by kwypchlo** [comment]
@m-cat actually those are all unit tests, dependencies are mocked and they test only the actual logic.

**Comment by m-cat** [comment]
@kwypchlo Undid the change and added function stubs in this PR

**Pull request merged**
